# Import Dependencies

In [38]:
import pandas as pd
from config import api_keyUSC, PG_key
from census import Census
from sqlalchemy import create_engine
import numpy as np

In [39]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect,func

In [40]:
import psycopg2

In [41]:
#import warnings
#from sqlalchemy import exc

# for warnings not included in regex-based filter below, just log
#warnings.filterwarnings(
  #"always", category=exc.RemovedIn20Warning
#)

# ASFIN

In [42]:
#import .csv file into DF
#note: currency values are in Thousands of Dollars

state_asfin_df = pd.read_csv ('2015_asfin_state_totals_transposed.csv')

In [43]:
state_asfin_df.set_index('State', inplace=True)
state_asfin_df.drop(['United States'], inplace = True)
state_asfin_df = state_asfin_df[['General expenditure','Education', 'Public welfare', 'Hospitals', 'Health','Police protection', 'Correction' ]]

state_asfin_df = state_asfin_df.rename(columns={'General expenditure':'Total General Expenditure','Education': 'Education Expediture', 'Public welfare':'Public Welfare Expenditure', 'Hospitals': 'Hospitals Expenditure', 'Health': 'Health Expenditure', 'Police protection':'Police Protection Expenditure', 'Correction':'Correction Expenditure'})

In [44]:
state_asfin_df.head()

,Total General Expenditure,Education Expediture,Public Welfare Expenditure,Hospitals Expenditure,Health Expenditure,Police Protection Expenditure,Correction Expenditure
State,,,,,,,
Alabama,"28,710,747","12,235,527","8,204,660","2,370,549","414,116","155,814","555,852"
Alaska,"11,580,917","2,703,274","2,113,211","68,984","283,698","161,965","340,726"
Arizona,"28,577,420","10,452,117","10,346,172","64,560","625,316","259,768","1,097,103"
Arkansas,"19,882,973","8,162,327","6,572,760","871,039","243,532","107,112","351,802"
California,"269,774,501","90,276,519","109,031,702","10,633,226","8,177,522","1,790,672","9,667,904"

# CENSUS

In [45]:
c = Census(api_keyUSC, year=2015)
census_data = c.acs5.get(("NAME", "B01003_001E", "B02001_003E",
                          "B02001_002E","B02001_005E","B03001_003E","B02001_008E",
                          "B17001_002E"), {'for': 'state:*'})

# Convert to DataFrame
census_df = pd.DataFrame(census_data)

# Column Reordering

census_df.drop('state', axis=1, inplace = True)
census_df = census_df.rename(columns={"NAME": "State",
                                      "B01003_001E": "Population",
                                      "B02001_003E": "Population Black",
                                      "B02001_002E": "Population White",
                                      "B02001_005E": "Population Asian",
                                      "B03001_003E": "Population Hispanic",
                                      "B02001_008E": "Population Mixed Race",
                                      "B17001_002E": "Poverty Count",
                                      })

# Add in Poverty Rate (Poverty Count / Population)
census_df["Poverty Rate"] = round(100 * \
    census_df["Poverty Count"].astype(
        int) / census_df["Population"].astype(int),2)

In [46]:
census_df = census_df.sort_values('State')
census_df.set_index('State', inplace=True)
census_df

,Population,Population Black,Population White,Population Asian,Population Hispanic,Population Mixed Race,Poverty Count,Poverty Rate
State,,,,,,,,
Alabama,4830620.00,1276544.00,3325464.00,59599.00,193492.00,81646.00,887260.00,18.37
Alaska,733375.00,25022.00,484250.00,42921.00,47808.00,61755.00,72957.00,9.95
Arizona,6641928.00,281576.00,5210335.00,200090.00,2014711.00,211845.00,1180690.00,17.78
Arkansas,2958208.00,459748.00,2307849.00,40336.00,203226.00,62537.00,553644.00,18.72
California,38421464.00,2265387.00,23747013.00,5261978.00,14750686.00,1734897.00,6135142.00,15.97
Colorado,5278906.00,213787.00,4446095.00,153467.00,1112586.00,183480.00,653969.00,12.39
Connecticut,3593222.00,370501.00,2778362.00,150670.00,526508.00,101919.00,366351.00,10.20
Delaware,926454.00,200481.00,642623.00,33643.00,80706.00,25266.00,108315.00,11.69
District of Columbia,647484.00,316447.00,260325.00,23822.00,65803.00,17327.00,110365.00,17.05
Florida,19645772.00,3171108.00,14934702.00,509085.00,4660733.00,472082.00,3180109.00,16.19
Georgia,10006693.00,3096757.00,6025691.00,360448.00,915120.00,213803.00,1788947.00,17.88
Hawaii,1406299.00,28688.00,357164.00,530551.00,139251.00,333119.00,153944.00,10.95
Idaho,1616547.00,9900.00,1482914.00,21711.00,191314.00,41226.00,245177.00,15.17
Illinois,12873761.00,1846108.00,9312771.00,645642.00,2122841.00,289537.00,1801118.00,13.99
Indiana,6568645.00,603014.00,5529201.00,121729.00,421206.00,145601.00,978043.00,14.89
Iowa,3093526.00,97788.00,2820046.00,62997.00,168230.00,60964.00,373883.00,12.09
Kansas,2892987.00,168402.00,2464566.00,75653.00,323218.00,95365.00,381353.00,13.18
Kentucky,4397353.00,347034.00,3851591.00,55483.00,143481.00,90836.00,805841.00,18.33
Louisiana,4625253.00,1484363.00,2902538.00,77818.00,218263.00,83877.00,888280.00,19.21
Maine,1329100.00,15037.00,1262026.00,14590.00,19447.00,26298.00,180278.00,13.56
Maryland,5930538.00,1750916.00,3416107.00,357616.00,533671.00,175652.00,576805.00,9.73
Massachusetts,6705586.00,478947.00,5334859.00,400675.00,707928.00,194677.00,748905.00,11.17
Michigan,9900571.00,1381388.00,7823875.00,268766.00,467021.00,261324.00,1616870.00,16.33
Minnesota,5419171.00,299176.00,4594367.00,240786.00,270984.00,144226.00,596662.00,11.01
Mississippi,2988081.00,1116457.00,1768174.00,28900.00,86507.00,35334.00,651545.00,21.80
Missouri,6045448.00,697022.00,4995527.00,106537.00,233046.00,147645.00,915972.00,15.15
Montana,1014699.00,4757.00,904977.00,7187.00,33622.00,25777.00,150586.00,14.84
Nebraska,1869365.00,88195.00,1647551.00,38066.00,186268.00,41595.00,231115.00,12.36
Nevada,2798636.00,235721.00,1929661.00,214846.00,770553.00,122935.00,426337.00,15.23
New Hampshire,1324201.00,17439.00,1241313.00,31364.00,42141.00,24346.00,113840.00,8.60
New Jersey,8904413.00,1202300.00,6083940.00,804989.00,1688008.00,223826.00,944847.00,10.61
New Mexico,2084117.00,43738.00,1524911.00,28761.00,986972.00,68053.00,429361.00,20.60
New York,19673174.00,3070392.00,12704637.00,1570223.00,3619658.00,560879.00,3005943.00,15.28
North Carolina,9845333.00,2115338.00,6839831.00,244076.00,869908.00,231391.00,1667465.00,16.94
North Dakota,721640.00,11872.00,640208.00,8979.00,20569.00,16132.00,79758.00,11.05
Ohio,11575977.00,1412045.00,9538328.00,216170.00,390970.00,287212.00,1775836.00,15.34
Oklahoma,3849733.00,278571.00,2813794.00,74570.00,371459.00,299936.00,624043.00,16.21
Oregon,3939233.00,72837.00,3352941.00,156695.00,485646.00,162793.00,636947.00,16.17
Pennsylvania,12779559.00,1403143.00,10430142.00,392595.00,815538.00,272689.00,1666569.00,13.04
Puerto Rico,3583073.00,301519.00,2495997.00,10159.00,3547288.00,332051.00,1616117.00,45.10
Rhode Island,1053661.00,68243.00,854859.00,34213.00,143788.00,29782.00,144223.00,13.69
South Carolina,4777576.00,1315058.00,3210708.00,66982.00,254092.00,93950.00,830901.00,17.39
South Dakota,843190.00,13133.00,716691.00,10152.00,27914.00,22323.00,114907.00,13.63
Tennessee,6499615.00,1091070.00,5059894.00,102027.00,320090.00,128760.00,1117594.00,17.19
Texas,26538614.00,3152917.00,19874610.00,1124011.00,10196367.00,653062.00,4472451.00,16.85
Utah,2903379.00,31909.00,2544735.00,64102.00,389856.00,74755.00,351601.00,12.11
Vermont,626604.00,6949.00,594443.00,8774.00,10691.00,12169.00,69233.00,11.05
Virginia,8256630.00,1589345.00,5695147.00,492973.00,709156.00,268167.00,921822.00,11.16
Washington,6985464.00,253224.00,5434177.00,535501.00,835488.00,360705.00,908512.00,13.01
West Virginia,1851420.00,61367.00,1732235.00,13485.00,25408.00,36189.00,323384.00,17.47
Wisconsin,5742117.00,360792.00,4967124.00,143732.00,364558.00,122730.00,724348.00,12.61
Wyoming,579679.00,6142.00,527763.00,5319.00,55698.00,15489.00,64995.00,11.21

In [47]:
#merge together
state_df = pd.merge(census_df,state_asfin_df, left_index=True, right_index=True)
state_df

,Population,Population Black,Population White,Population Asian,Population Hispanic,Population Mixed Race,Poverty Count,Poverty Rate,Total General Expenditure,Education Expediture,Public Welfare Expenditure,Hospitals Expenditure,Health Expenditure,Police Protection Expenditure,Correction Expenditure
State,,,,,,,,,,,,,,,
Alabama,4830620.00,1276544.00,3325464.00,59599.00,193492.00,81646.00,887260.00,18.37,"28,710,747","12,235,527","8,204,660","2,370,549","414,116","155,814","555,852"
Alaska,733375.00,25022.00,484250.00,42921.00,47808.00,61755.00,72957.00,9.95,"11,580,917","2,703,274","2,113,211","68,984","283,698","161,965","340,726"
Arizona,6641928.00,281576.00,5210335.00,200090.00,2014711.00,211845.00,1180690.00,17.78,"28,577,420","10,452,117","10,346,172","64,560","625,316","259,768","1,097,103"
Arkansas,2958208.00,459748.00,2307849.00,40336.00,203226.00,62537.00,553644.00,18.72,"19,882,973","8,162,327","6,572,760","871,039","243,532","107,112","351,802"
California,38421464.00,2265387.00,23747013.00,5261978.00,14750686.00,1734897.00,6135142.00,15.97,"269,774,501","90,276,519","109,031,702","10,633,226","8,177,522","1,790,672","9,667,904"
Colorado,5278906.00,213787.00,4446095.00,153467.00,1112586.00,183480.00,653969.00,12.39,"26,917,961","10,988,746","7,927,080","827,482","427,722","178,366","1,022,917"
Connecticut,3593222.00,370501.00,2778362.00,150670.00,526508.00,101919.00,366351.00,10.20,"22,311,191","7,728,457","4,256,901","1,416,163","949,526","256,502","700,694"
Delaware,926454.00,200481.00,642623.00,33643.00,80706.00,25266.00,108315.00,11.69,"8,045,313","3,027,509","2,288,305","90,693","406,718","140,054","304,986"
Florida,19645772.00,3171108.00,14934702.00,509085.00,4660733.00,472082.00,3180109.00,16.19,"76,164,790","25,023,832","25,776,510","1,054,547","3,663,682","551,849","2,475,144"
Georgia,10006693.00,3096757.00,6025691.00,360448.00,915120.00,213803.00,1788947.00,17.88,"39,023,326","17,276,438","11,969,354","1,274,505","1,210,283","360,669","1,208,635"
Hawaii,1406299.00,28688.00,357164.00,530551.00,139251.00,333119.00,153944.00,10.95,"10,504,000","3,179,124","2,558,379","659,902","484,996","36,790","212,812"
Idaho,1616547.00,9900.00,1482914.00,21711.00,191314.00,41226.00,245177.00,15.17,"7,711,133","2,786,541","2,334,833","46,630","106,054","58,637","256,902"
Illinois,12873761.00,1846108.00,9312771.00,645642.00,2122841.00,289537.00,1801118.00,13.99,"71,652,058","18,032,033","24,395,723","757,268","1,230,305","413,036","1,502,405"
Indiana,6568645.00,603014.00,5529201.00,121729.00,421206.00,145601.00,978043.00,14.89,"34,470,175","14,801,529","11,563,940","143,620","454,447","225,038","687,837"
Iowa,3093526.00,97788.00,2820046.00,62997.00,168230.00,60964.00,373883.00,12.09,"19,894,554","7,129,439","5,905,922","1,727,315","203,481","100,780","294,185"
Kansas,2892987.00,168402.00,2464566.00,75653.00,323218.00,95365.00,381353.00,13.18,"16,149,962","7,010,167","3,825,630","1,711,494","364,256","103,785","359,801"
Kentucky,4397353.00,347034.00,3851591.00,55483.00,143481.00,90836.00,805841.00,18.33,"29,182,828","9,614,803","10,875,235","1,572,995","427,761","196,160","542,193"
Louisiana,4625253.00,1484363.00,2902538.00,77818.00,218263.00,83877.00,888280.00,19.21,"26,154,618","8,897,506","8,399,355","355,809","364,693","326,366","672,298"
Maine,1329100.00,15037.00,1262026.00,14590.00,19447.00,26298.00,180278.00,13.56,"7,548,525","2,035,487","3,011,951","94,039","172,886","76,304","152,969"
Maryland,5930538.00,1750916.00,3416107.00,357616.00,533671.00,175652.00,576805.00,9.73,"38,041,607","12,168,535","12,174,866","542,067","2,130,721","601,949","1,476,397"
Massachusetts,6705586.00,478947.00,5334859.00,400675.00,707928.00,194677.00,748905.00,11.17,"51,122,359","12,323,712","19,895,426","760,148","928,106","577,613","1,378,933"
Michigan,9900571.00,1381388.00,7823875.00,268766.00,467021.00,261324.00,1616870.00,16.33,"59,085,103","24,211,552","18,410,125","3,422,936","1,194,651","470,963","1,888,248"
Minnesota,5419171.00,299176.00,4594367.00,240786.00,270984.00,144226.00,596662.00,11.01,"37,570,750","14,289,649","12,761,965","297,779","431,389","436,648","528,792"
Mississippi,2988081.00,1116457.00,1768174.00,28900.00,86507.00,35334.00,651545.00,21.80,"18,354,508","5,791,535","6,228,236","1,257,672","340,349","162,829","371,359"
Missouri,6045448.00,697022.00,4995527.00,106537.00,233046.00,147645.00,915972.00,15.15,"27,826,546","9,507,971","8,676,992","1,858,510","1,659,447","250,460","770,323"
Montana,1014699.00,4757.00,904977.00,7187.00,33622.00,25777.00,150586.00,14.84,"5,691,082","1,798,401","1,459,870","52,666","118,398","53,776","203,181"
Nebraska,1869365.00,88195.00,1647551.00,38066.00,186268.00,41595.00,231115.00,12.36,"9,664,338","3,593,464","2,493,798","266,398","276,120","82,705","349,077"
Nevada,2798636.00,235721.00,1929661.00,214846.00,770553.00,122935.00,426337.00,15.23,"11,662,037","4,714,642","3,154,084","225,109","227,383","77,752","258,420"
New Hampshire,1324201.00,17439.00,1241313.00,31364.00,42141.00,24346.00,113840.00,8.60,"6,764,330","2,277,515","2,106,083","55,161","93,285","62,687","121,853"
New Jersey,8904413.00,1202300.00,6083940.00,804989.00,1688008.00,223826.00,944847.00,10.61,"60,697,956","22,285,616","17,094,670","2,051,020","2,874,076","831,284","1,471,630"
New Mexico,2084117.00,43738.00,1524911.00,28761.00,986972.00,68053.00,429361.00,20.60,"17,816,434","5,840,534","5,689,510","1,027,289","314,763","145,509","456,721"
New York,19673174.00,3070392.00,12704637.00,1570223.00,3619658.00,560879.00,3005943.00,15.28,"151,427,270","43,024,231","58,001,659","5,006,495","8,271,505","904,891","3,075,600"
North Carolina,9845333.00,2115338.00,6839831.00,244076.00,869908.00,231391.00,1667465.00,16.94,"49,010,718","19,912,132","14,560,381","1,804,269","1,343,179","506,044","1,270,111"
North Dakota,721640.00,11872.00,640208.00,8979.00,20569.00,16132.00,79758.00,11.05,"7,161,778","2,307,999","1,385,251","52,200","129,752","37,021","91,486"
Ohio,11575977.00,1412045.00,9538328.00,216170.00,390970.00,287212.00,1775836.00,15.34,"65,287,289","22,208,885","25,344,578","3,047,779","1,664,178","360,237","1,589,278"
Oklahoma,3849733.00,278571.00,2813794.00,74570.00,371459.00,299936.00,624043.00,16.21,"20,704,332","7,672,357","6,693,834","216,162","824,036","181,741","567,034"
Oregon,3939233.00,72837.00,3352941.00,156695.00,485646.00,162793.00,636947.00,16.17,"28,688,736","8,997,319","9,870,345","2,150,063","607,119","176,304","777,917"
Pennsylvania,12779559.00,1403143.00,10430142.00,392595.00,815538.00,272689.00,1666569.00,13.04,"76,641,318","24,204,413","24,655,737","4,231,964","3,086,492","1,052,778","2,099,219"
Rhode Island,1053661.00,68243.00,854859.00,34213.00,143788.00,29782.00,144223.00,13.69,"7,535,554","1,981,863","3,008,751","56,811","184,434","87,957","201,365"
South Carolina,4777576.00,1315058.00,3210708.00,66982.00,254092.00,93950.00,830901.00,17.39,"25,224,165","9,160,360","7,594,043","1,637,482","1,003,641","167,268","458,406"
South Dakota,843190.00,13133.00,716691.00,10152.00,27914.00,22323.00,114907.00,13.63,"4,263,678","1,320,602","1,101,035","23,640","125,551","45,414","125,955"
Tennessee,6499615.00,1091070.00,5059894.00,102027.00,320090.00,128760.00,1117594.00,17.19,"28,340,888","10,131,629","11,235,158","347,785","612,458","208,743","903,791"
Texas,26538614.00,3152917.00,19874610.00,1124011.00,10196367.00,653062.00,4472451.00,16.85,"119,937,919","51,934,894","36,204,845","6,970,243","2,509,135","1,000,389","3,848,272"
Utah,2903379.00,31909.00,2544735.00,64102.00,389856.00,74755.00,351601.00,12.11,"16,423,836","7,444,709","3,428,679","1,501,057","254,522","144,063","342,133"
Vermont,626604.00,6949.00,594443.00,8774.00,10691.00,12169.00,69233.00,11.05,"6,166,657","2,596,210","1,750,376","19,328","334,625","99,220","145,129"
Virginia,8256630.00,1589345.00,5695147.00,492973.00,709156.00,268167.00,921822.00,11.16,"44,870,128","15,981,360","9,986,797","4,417,363","1,215,670","426,084","1,453,297"
Washington,6985464.00,253224.00,5434177.00,535501.00,835488.00,360705.00,908512.00,13.01,"43,875,706","17,101,172","11,329,491","2,586,923","2,239,003","405,692","984,771"
West Virginia,1851420.00,61367.00,1732235.00,13485.00,25408.00,36189.00,323384.00,17.47,"12,790,705","4,440,368","4,651,087","136,349","264,918","73,554","285,324"
Wisconsin,5742117.00,360792.00,4967124.00,143732.00,364558.00,122730.00,724348.00,12.61,"34,899,560","11,752,333","9,955,799","1,877,692","724,909","96,946","1,125,914"
Wyoming,579679.00,6142.00,527763.00,5319.00,55698.00,15489.00,64995.00,11.21,"5,232,487","2,020,840","799,594","3,442","228,679","39,244","143,520"

In [48]:
#convert index to match the other datasets
us_state_abbrev = {
   'Alabama': 'AL',
   'Alaska': 'AK',
   'Arizona': 'AZ',
   'Arkansas': 'AR',
   'California': 'CA',
   'Colorado': 'CO',
   'Connecticut': 'CT',
   'Delaware': 'DE',
   'Florida': 'FL',
   'Georgia': 'GA',
   'Hawaii': 'HI',
   'Idaho': 'ID',
   'Illinois': 'IL',
   'Indiana': 'IN',
   'Iowa': 'IA',
   'Kansas': 'KS',
   'Kentucky': 'KY',
   'Louisiana': 'LA',
   'Maine': 'ME',
   'Maryland': 'MD',
   'Massachusetts': 'MA',
   'Michigan': 'MI',
   'Minnesota': 'MN',
   'Mississippi': 'MS',
   'Missouri': 'MO',
   'Montana': 'MT',
   'Nebraska': 'NE',
   'Nevada': 'NV',
   'New Hampshire': 'NH',
   'New Jersey': 'NJ',
   'New Mexico': 'NM',
   'New York': 'NY',
   'North Carolina': 'NC',
   'North Dakota': 'ND',
   'Ohio': 'OH',
   'Oklahoma': 'OK',
   'Oregon': 'OR',
   'Pennsylvania': 'PA',
   'Rhode Island': 'RI',
   'South Carolina': 'SC',
   'South Dakota': 'SD',
   'Tennessee': 'TN',
   'Texas': 'TX',
   'Utah': 'UT',
   'Vermont': 'VT',
   'Virginia': 'VA',
   'Washington': 'WA',
   'West Virginia': 'WV',
   'Wisconsin': 'WI',
   'Wyoming': 'WY'}

state_df.index = state_df.index.map(us_state_abbrev)

In [49]:
#verify dtypes 
state_df.dtypes

Population                       float64
Population Black                 float64
Population White                 float64
Population Asian                 float64
Population Hispanic              float64
Population Mixed Race            float64
Poverty Count                    float64
Poverty Rate                     float64
Total General Expenditure         object
Education Expediture              object
Public Welfare Expenditure        object
Hospitals Expenditure             object
Health Expenditure                object
Police Protection Expenditure     object
Correction Expenditure            object
dtype: object

In [50]:
#format values & convert from string to numeric
state_df = state_df.replace(',','', regex=True)
c = state_df.select_dtypes(object).columns
state_df[c] = state_df[c].apply(pd.to_numeric,errors='coerce')

#format the expenditure totals to true value (original values in thousands of $)
for column in state_df.iloc[:,8:15]:
        new_column = []
        for index, row in state_df.iterrows():
            new_value = ((row[column])* 1000)
            new_column.append(new_value)
        state_df[column]= new_column   
        pd.set_option('display.float_format','{:.2f}'.format)
state_df.head()

,Population,Population Black,Population White,Population Asian,Population Hispanic,Population Mixed Race,Poverty Count,Poverty Rate,Total General Expenditure,Education Expediture,Public Welfare Expenditure,Hospitals Expenditure,Health Expenditure,Police Protection Expenditure,Correction Expenditure
State,,,,,,,,,,,,,,,
AL,4830620.00,1276544.00,3325464.00,59599.00,193492.00,81646.00,887260.00,18.37,28710747000.00,12235527000.00,8204660000.00,2370549000.00,414116000.00,155814000.00,555852000.00
AK,733375.00,25022.00,484250.00,42921.00,47808.00,61755.00,72957.00,9.95,11580917000.00,2703274000.00,2113211000.00,68984000.00,283698000.00,161965000.00,340726000.00
AZ,6641928.00,281576.00,5210335.00,200090.00,2014711.00,211845.00,1180690.00,17.78,28577420000.00,10452117000.00,10346172000.00,64560000.00,625316000.00,259768000.00,1097103000.00
AR,2958208.00,459748.00,2307849.00,40336.00,203226.00,62537.00,553644.00,18.72,19882973000.00,8162327000.00,6572760000.00,871039000.00,243532000.00,107112000.00,351802000.00
CA,38421464.00,2265387.00,23747013.00,5261978.00,14750686.00,1734897.00,6135142.00,15.97,269774501000.00,90276519000.00,109031702000.00,10633226000.00,8177522000.00,1790672000.00,9667904000.00

In [51]:
#build out new columns with the true per capita $ amount state are spending in each category
# * by 1000 bc original spending values were in thousands 
for column in state_df.iloc[:,8:15]:
        new_column_percap = []
        new_column_percent = []
        for index, row in state_df.iterrows():
                per_capita = (row[column])/(row['Population'])
                new_column_percap.append(per_capita)
                percent = (row[column])/(row['Total General Expenditure'])*100
                new_column_percent.append(percent)
        state_df[column +' per capita'] = new_column_percap
        state_df[column +' Percentage of Budget'] = new_column_percent

In [52]:
#build out new columns with the percentage of the total population each race category is 
for column in state_df.iloc[:,1:6]:
        new_column = []
        for index, row in state_df.iterrows():
                percent = (row[column])/(row['Population'])*100
                new_column.append(percent)
        state_df[column +' Percentage'] = new_column

In [53]:
state_df

,Population,Population Black,Population White,Population Asian,Population Hispanic,Population Mixed Race,Poverty Count,Poverty Rate,Total General Expenditure,Education Expediture,...,Health Expenditure Percentage of Budget,Police Protection Expenditure per capita,Police Protection Expenditure Percentage of Budget,Correction Expenditure per capita,Correction Expenditure Percentage of Budget,Population Black Percentage,Population White Percentage,Population Asian Percentage,Population Hispanic Percentage,Population Mixed Race Percentage
State,,,,,,,,,,,,,,,,,,,,,
AL,4830620.00,1276544.00,3325464.00,59599.00,193492.00,81646.00,887260.00,18.37,28710747000.00,12235527000.00,...,1.44,32.26,0.54,115.07,1.94,26.43,68.84,1.23,4.01,1.69
AK,733375.00,25022.00,484250.00,42921.00,47808.00,61755.00,72957.00,9.95,11580917000.00,2703274000.00,...,2.45,220.85,1.40,464.60,2.94,3.41,66.03,5.85,6.52,8.42
AZ,6641928.00,281576.00,5210335.00,200090.00,2014711.00,211845.00,1180690.00,17.78,28577420000.00,10452117000.00,...,2.19,39.11,0.91,165.18,3.84,4.24,78.45,3.01,30.33,3.19
AR,2958208.00,459748.00,2307849.00,40336.00,203226.00,62537.00,553644.00,18.72,19882973000.00,8162327000.00,...,1.22,36.21,0.54,118.92,1.77,15.54,78.02,1.36,6.87,2.11
CA,38421464.00,2265387.00,23747013.00,5261978.00,14750686.00,1734897.00,6135142.00,15.97,269774501000.00,90276519000.00,...,3.03,46.61,0.66,251.63,3.58,5.90,61.81,13.70,38.39,4.52
CO,5278906.00,213787.00,4446095.00,153467.00,1112586.00,183480.00,653969.00,12.39,26917961000.00,10988746000.00,...,1.59,33.79,0.66,193.77,3.80,4.05,84.22,2.91,21.08,3.48
CT,3593222.00,370501.00,2778362.00,150670.00,526508.00,101919.00,366351.00,10.20,22311191000.00,7728457000.00,...,4.26,71.38,1.15,195.00,3.14,10.31,77.32,4.19,14.65,2.84
DE,926454.00,200481.00,642623.00,33643.00,80706.00,25266.00,108315.00,11.69,8045313000.00,3027509000.00,...,5.06,151.17,1.74,329.20,3.79,21.64,69.36,3.63,8.71,2.73
FL,19645772.00,3171108.00,14934702.00,509085.00,4660733.00,472082.00,3180109.00,16.19,76164790000.00,25023832000.00,...,4.81,28.09,0.72,125.99,3.25,16.14,76.02,2.59,23.72,2.40
GA,10006693.00,3096757.00,6025691.00,360448.00,915120.00,213803.00,1788947.00,17.88,39023326000.00,17276438000.00,...,3.10,36.04,0.92,120.78,3.10,30.95,60.22,3.60,9.15,2.14
HI,1406299.00,28688.00,357164.00,530551.00,139251.00,333119.00,153944.00,10.95,10504000000.00,3179124000.00,...,4.62,26.16,0.35,151.33,2.03,2.04,25.40,37.73,9.90,23.69
ID,1616547.00,9900.00,1482914.00,21711.00,191314.00,41226.00,245177.00,15.17,7711133000.00,2786541000.00,...,1.38,36.27,0.76,158.92,3.33,0.61,91.73,1.34,11.83,2.55
IL,12873761.00,1846108.00,9312771.00,645642.00,2122841.00,289537.00,1801118.00,13.99,71652058000.00,18032033000.00,...,1.72,32.08,0.58,116.70,2.10,14.34,72.34,5.02,16.49,2.25
IN,6568645.00,603014.00,5529201.00,121729.00,421206.00,145601.00,978043.00,14.89,34470175000.00,14801529000.00,...,1.32,34.26,0.65,104.72,2.00,9.18,84.18,1.85,6.41,2.22
IA,3093526.00,97788.00,2820046.00,62997.00,168230.00,60964.00,373883.00,12.09,19894554000.00,7129439000.00,...,1.02,32.58,0.51,95.10,1.48,3.16,91.16,2.04,5.44,1.97
KS,2892987.00,168402.00,2464566.00,75653.00,323218.00,95365.00,381353.00,13.18,16149962000.00,7010167000.00,...,2.26,35.87,0.64,124.37,2.23,5.82,85.19,2.62,11.17,3.30
KY,4397353.00,347034.00,3851591.00,55483.00,143481.00,90836.00,805841.00,18.33,29182828000.00,9614803000.00,...,1.47,44.61,0.67,123.30,1.86,7.89,87.59,1.26,3.26,2.07
LA,4625253.00,1484363.00,2902538.00,77818.00,218263.00,83877.00,888280.00,19.21,26154618000.00,8897506000.00,...,1.39,70.56,1.25,145.35,2.57,32.09,62.75,1.68,4.72,1.81
ME,1329100.00,15037.00,1262026.00,14590.00,19447.00,26298.00,180278.00,13.56,7548525000.00,2035487000.00,...,2.29,57.41,1.01,115.09,2.03,1.13,94.95,1.10,1.46,1.98
MD,5930538.00,1750916.00,3416107.00,357616.00,533671.00,175652.00,576805.00,9.73,38041607000.00,12168535000.00,...,5.60,101.50,1.58,248.95,3.88,29.52,57.60,6.03,9.00,2.96
MA,6705586.00,478947.00,5334859.00,400675.00,707928.00,194677.00,748905.00,11.17,51122359000.00,12323712000.00,...,1.82,86.14,1.13,205.64,2.70,7.14,79.56,5.98,10.56,2.90
MI,9900571.00,1381388.00,7823875.00,268766.00,467021.00,261324.00,1616870.00,16.33,59085103000.00,24211552000.00,...,2.02,47.57,0.80,190.72,3.20,13.95,79.02,2.71,4.72,2.64
MN,5419171.00,299176.00,4594367.00,240786.00,270984.00,144226.00,596662.00,11.01,37570750000.00,14289649000.00,...,1.15,80.57,1.16,97.58,1.41,5.52,84.78,4.44,5.00,2.66
MS,2988081.00,1116457.00,1768174.00,28900.00,86507.00,35334.00,651545.00,21.80,18354508000.00,5791535000.00,...,1.85,54.49,0.89,124.28,2.02,37.36,59.17,0.97,2.90,1.18
MO,6045448.00,697022.00,4995527.00,106537.00,233046.00,147645.00,915972.00,15.15,27826546000.00,9507971000.00,...,5.96,41.43,0.90,127.42,2.77,11.53,82.63,1.76,3.85,2.44
MT,1014699.00,4757.00,904977.00,7187.00,33622.00,25777.00,150586.00,14.84,5691082000.00,1798401000.00,...,2.08,53.00,0.94,200.24,3.57,0.47,89.19,0.71,3.31,2.54
NE,1869365.00,88195.00,1647551.00,38066.00,186268.00,41595.00,231115.00,12.36,9664338000.00,3593464000.00,...,2.86,44.24,0.86,186.74,3.61,4.72,88.13,2.04,9.96,2.23
NV,2798636.00,235721.00,1929661.00,214846.00,770553.00,122935.00,426337.00,15.23,11662037000.00,4714642000.00,...,1.95,27.78,0.67,92.34,2.22,8.42,68.95,7.68,27.53,4.39
NH,1324201.00,17439.00,1241313.00,31364.00,42141.00,24346.00,113840.00,8.60,6764330000.00,2277515000.00,...,1.38,47.34,0.93,92.02,1.80,1.32,93.74,2.37,3.18,1.84
NJ,8904413.00,1202300.00,6083940.00,804989.00,1688008.00,223826.00,944847.00,10.61,60697956000.00,22285616000.00,...,4.74,93.36,1.37,165.27,2.42,13.50,68.32,9.04,18.96,2.51
NM,2084117.00,43738.00,1524911.00,28761.00,986972.00,68053.00,429361.00,20.60,17816434000.00,5840534000.00,...,1.77,69.82,0.82,219.14,2.56,2.10,73.17,1.38,47.36,3.27
NY,19673174.00,3070392.00,12704637.00,1570223.00,3619658.00,560879.00,3005943.00,15.28,151427270000.00,43024231000.00,...,5.46,46.00,0.60,156.33,2.03,15.61,64.58,7.98,18.40,2.85
NC,9845333.00,2115338.00,6839831.00,244076.00,869908.00,231391.00,1667465.00,16.94,49010718000.00,19912132000.00,...,2.74,51.40,1.03,129.01,2.59,21.49,69.47,2.48,8.84,2.35
ND,721640.00,11872.00,640208.00,8979.00,20569.00,16132.00,79758.00,11.05,7161778000.00,2307999000.00,...,1.81,51.30,0.52,126.78,1.28,1.65,88.72,1.24,2.85,2.24
OH,11575977.00,1412045.00,9538328.00,216170.00,390970.00,287212.00,1775836.00,15.34,65287289000.00,22208885000.00,...,2.55,31.12,0.55,137.29,2.43,12.20,82.40,1.87,3.38,2.48
OK,3849733.00,278571.00,2813794.00,74570.00,371459.00,299936.00,624043.00,16.21,20704332000.00,7672357000.00,...,3.98,47.21,0.88,147.29,2.74,7.24,73.09,1.94,9.65,7.79
OR,3939233.00,72837.00,3352941.00,156695.00,485646.00,162793.00,636947.00,16.17,28688736000.00,8997319000.00,...,2.12,44.76,0.61,197.48,2.71,1.85,85.12,3.98,12.33,4.13
PA,12779559.00,1403143.00,10430142.00,392595.00,815538.00,272689.00,1666569.00,13.04,76641318000.00,24204413000.00,...,4.03,82.38,1.37,164.26,2.74,10.98,81.62,3.07,6.38,2.13
RI,1053661.00,68243.00,854859.00,34213.00,143788.00,29782.00,144223.00,13.69,7535554000.00,1981863000.00,...,2.45,83.48,1.17,191.11,2.67,6.48,81.13,3.25,13.65,2.83
SC,4777576.00,1315058.00,3210708.00,66982.00,254092.00,93950.00,830901.00,17.39,25224165000.00,9160360000.00,...,3.98,35.01,0.66,95.95,1.82,27.53,67.20,1.40,5.32,1.97
SD,843190.00,13133.00,716691.00,10152.00,27914.00,22323.00,114907.00,13.63,4263678000.00,1320602000.00,...,2.94,53.86,1.07,149.38,2.95,1.56,85.00,1.20,3.31,2.65
TN,6499615.00,1091070.00,5059894.00,102027.00,320090.00,128760.00,1117594.00,17.19,28340888000.00,10131629000.00,...,2.16,32.12,0.74,139.05,3.19,16.79,77.85,1.57,4.92,1.98
TX,26538614.00,3152917.00,19874610.00,1124011.00,10196367.00,653062.00,4472451.00,16.85,119937919000.00,51934894000.00,...,2.09,37.70,0.83,145.01,3.21,11.88,74.89,4.24,38.42,2.46
UT,2903379.00,31909.00,2544735.00,64102.00,389856.00,74755.00,351601.00,12.11,16423836000.00,7444709000.00,...,1.55,49.62,0.88,117.84,2.08,1.10,87.65,2.21,13.43,2.57
VT,626604.00,6949.00,594443.00,8774.00,10691.00,12169.00,69233.00,11.05,6166657000.00,2596210000.00,...,5.43,158.35,1.61,231.61,2.35,1.11,94.87,1.40,1.71,1.94
VA,8256630.00,1589345.00,5695147.00,492973.00,709156.00,268167.00,921822.00,11.16,44870128000.00,15981360000.00,...,2.71,51.61,0.95,176.02,3.24,19.25,68.98,5.97,8.59,3.25
WA,6985464.00,253224.00,5434177.00,535501.00,835488.00,360705.00,908512.00,13.01,43875706000.00,17101172000.00,...,5.10,58.08,0.92,140.97,2.24,3.63,77.79,7.67,11.96,5.16
WV,1851420.00,61367.00,1732235.00,13485.00,25408.00,36189.00,323384.00,17.47,12790705000.00,4440368000.00,...,2.07,39.73,0.58,154.11,2.23,3.31,93.56,0.73,1.37,1.95
WI,5742117.00,360792.00,4967124.00,143732.00,364558.00,122730.00,724348.00,12.61,34899560000.00,11752333000.00,...,2.08,16.88,0.28,196.08,3.23,6.28,86.50,2.50,6.35,2.14
WY,579679.00,6142.00,527763.00,5319.00,55698.00,15489.00,64995.00,11.21,5232487000.00,2020840000.00,...,4.37,67.70,0.75,247.59,2.74,1.06,91.04,0.92,9.61,2.67

# POLICE DEATHS

In [11]:
csv_file = "police_deaths.csv"
police_deaths_df = pd.read_csv(csv_file)
police_deaths_df.head()

,person,dept,eow,cause,cause_short,date,year,canine,dept_name,state
0,Constable Darius Quimby,"Albany County Constable's Office, NY","EOW: Monday, January 3, 1791",Cause of Death: Gunfire,Gunfire,1791-01-03,1791,False,Albany County Constable's Office,NY
1,Sheriff Cornelius Hogeboom,"Columbia County Sheriff's Office, NY","EOW: Saturday, October 22, 1791",Cause of Death: Gunfire,Gunfire,1791-10-22,1791,False,Columbia County Sheriff's Office,NY
2,Deputy Sheriff Isaac Smith,"Westchester County Sheriff's Department, NY","EOW: Thursday, May 17, 1792",Cause of Death: Gunfire,Gunfire,1792-05-17,1792,False,Westchester County Sheriff's Department,NY
3,Marshal Robert Forsyth,United States Department of Justice - United S...,"EOW: Saturday, January 11, 1794",Cause of Death: Gunfire,Gunfire,1794-01-11,1794,False,United States Department of Justice - United S...,US
4,Sheriff Robert Maxwell,"Greenville County Sheriff's Office, SC","EOW: Sunday, November 12, 1797",Cause of Death: Gunfire,Gunfire,1797-11-12,1797,False,Greenville County Sheriff's Office,SC

In [12]:
#Create filtered dataframe with specific columns
deaths_columns = ["year", "cause_short", "state"]
police_deaths_transformed = police_deaths_df[deaths_columns].copy()

In [13]:
#Rename the column headers
police_deaths_transformed = police_deaths_transformed.rename(columns = {"year" : "id"})
police_deaths_transformed.head()

     id cause_short state
0  1791     Gunfire    NY
1  1791     Gunfire    NY
2  1792     Gunfire    NY
3  1794     Gunfire    US
4  1797     Gunfire    SC

In [14]:
#Set index
police_deaths_transformed.set_index("id", inplace=True)
police_deaths_transformed.head()

     cause_short state
id
1791     Gunfire    NY
1791     Gunfire    NY
1792     Gunfire    NY
1794     Gunfire    US
1797     Gunfire    SC

In [15]:
#loc data on year 2015
year_filtered= police_deaths_transformed.loc['2015']
year_filtered.head()

              cause_short state
id
2015    Struck by vehicle    CO
2015         Heart attack    MO
2015      Vehicle pursuit    MD
2015  Automobile accident    TX
2015  Automobile accident    TX

In [16]:
#Create filter to get gunfire deaths only
gunfire_filtered= year_filtered.loc[year_filtered['cause_short'] == 'Gunfire']
gunfire_filtered.head()

     cause_short state
id
2015     Gunfire    GA
2015     Gunfire    PA
2015     Gunfire    US
2015     Gunfire    TR
2015     Gunfire    CA

In [17]:
#Group data by state
state_grouped = gunfire_filtered.groupby("state").count()
#Rename the column headers
state_grouped_df = state_grouped.rename(columns = {"cause_short" : "police_shooting_deaths"})
state_grouped_df.head()

       police_shooting_deaths
state
 AR                         1
 CA                         4
 CO                         1
 FL                         1
 GA                         1

# Police Killings

In [ ]:
#Clean up the look of the df step one( show all columns)
#===============================================================
pd.options.display.max_columns = None

In [ ]:
police_killings_df = pd.read_csv("police_killings(Dwayne)/police_killings.csv")
display(police_killings_df)

In [ ]:
#Changing the name of the dataframe
df = pd.DataFrame(police_killings_df)
df.head()

In [ ]:
#Using shape to count how many columns and rows are in the dateframe
#====================================================================
df.shape

In [ ]:
#Remove the columns that we found unneccessary for our analysis
#===============================================================================================================
df.drop(df.columns[[2,10,11,12,13,14,15,16,17,18,21,22,23,24,25,26,27,28,29,30,31,32,33]], axis=1, inplace=True)

In [ ]:
#Check out results
#============================================
display(df)

In [ ]:
#Rename columns
#=============================================================================
df.rename(columns = {
                    'name': 'Name',
                    'age': 'Age',
                    'raceethnicity': 'Ethnicity',
                    'month': 'Month',
                    'day': 'Day',
                    'year': 'Year', 
                    'street address':'Street Address',
                    'city': 'City',
                    'state': 'State',
                    'cause': "Cause of Death",
                    'armed': 'Armed'
}, inplace=True)

In [ ]:
#Check results
display(df)

In [ ]:
rds_connection_string = "postgres:postgres@localhost:5432/police_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [ ]:
inspector =inspect(engine)

In [ ]:
inspector.get_table_names()

In [ ]:
#Using the inspector to print the column names within the 'Police_killings' table and its types
columns = inspector.get_columns('police_killings')
for column in columns:
    print(column["name"], column["type"])

In [ ]:
#Load DataFrames into database 
df.to_sql(name='scrubbed_police_killings', con=engine, if_exists='append', index=True)

In [ ]:
#Confirmation on Scrubbed
pd.read_sql_query('select * from scrubbed_police_killings', con=engine).head()

#

In [82]:
#Create database connection
connection_string = "username:password@localhost:5432/shootings"
engine = create_engine(f'postgresql://{connection_string}')

In [83]:
#confirm table
engine.table_names()

<ipython-input-83-208f519aad61>:2: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['police_deaths']

In [85]:
dataframe.to_sql(name='table name', con=engine, if_exists='append', index= True)